import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Aletheia-Startup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body>
        
        <header>
          <Header/>
        </header>

            {children}

        <footer>
         <Footer/>
        </footer>

      </body>
    </html>
  );
}
